apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redisinsight.fullname" . }}
  labels:
    {{- include "redisinsight.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "redisinsight.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "redisinsight.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "redisinsight.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: db
          emptyDir: {}
        {{- if .Values.proxy.enabled }}
        - name: nginx-cm
          configMap:
            name: {{ include "redisinsight.fullname" . }}-nginx-cm
        {{- if .Values.proxy.tls.tlsEnabled }}
        - name: ssl-certs 
          secret:
            secretName: {{ .Values.proxy.tls.tlsSecret }}
        {{- end}}
        {{- end}}
      containers:
        {{- if .Values.proxy.enabled }}
        - name: proxy
          image: nginx
          volumeMounts:
            - name: nginx-cm
              mountPath: /etc/nginx/
            {{- if .Values.proxy.tls.tlsEnabled }}
            - name: ssl-certs
              mountPath: "/etc/ssl/proxy/"
              readOnly: true
            {{- end }}
          command: ["/docker-entrypoint.sh"]
          args: ["nginx"]
          env:
            - name: FORWARD_HOST
              value: "localhost"
            - name: FORWARD_PORT
              value: "8001"
            - name: NGINX_PORT
              value: "{{.Values.proxy.nginxPort }}"
        {{- end}}
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: RIPORT
            value: "8001"
          {{- if .Values.proxy.tls.tlsEnabled }}
          - name: RITRUSTEDORIGINS
            value: "https://redisinsight.external.domain"
          {{- else }}
          - name: RITRUSTEDORIGINS
            value: "http://redisinsight.external.domain"
          {{- end }}
          ports:
            - name: http
              containerPort: 8001
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /healthcheck/
          #     port: 8001
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
          #   failureThreshold: 1
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: db
              mountPath: /db
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
