apiVersion: v1
kind: Service
metadata:
  name: {{ include "redisinsight.fullname" . }}
  labels:
    {{- include "redisinsight.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if .Values.proxy.enabled }}
      targetPort: 9000
      {{- else}}
      targetPort: 8001
      {{- end}}
      protocol: TCP
      name: http
  selector:
    {{- include "redisinsight.selectorLabels" . | nindent 4 }}
